name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Format
        run: npm run fmtcheck
      - name: "check for uncommitted changes"
         # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
            || (echo "##[warning] found changed files after build. please 'npm run build && npm run fmt' and check in all changes")
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist/index.js
